# Generated by Django 4.2.2 on 2023-12-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('report', models.TextField(blank=True)),
                ('report_date', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
