# Generated by Django 4.2.2 on 2023-12-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_adminreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_model', models.CharField(blank=True, max_length=100)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('veh_color', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
